a = 15 * 3
b = 15 / 3
c = 15 // 2
d = 15 ** 2
type_a = type(a)
type_b = type(b)
type_c = type(c)
type_d = type(d)
print('1) 15 * 3, result = ' + str(a) + ' , ' + str(type_a))
print('2) 15 / 3, result = ' + str(b) + ' , ' + str(type_b))
print('3) 15 // 2, result = ' + str(c) + ' , ' + str(type_c))
print('4) 15 ** 2, result = ' + str(d) + ' , ' + str(type_d))
